version: "3.8"

networks:
  ghotos_dev:

volumes:
  db_data_dev: {}

services:
  app:
    container_name: ghotos_app_dev
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - ./docker/app/.env
    ports:
      - "4090:8080"
    volumes:
      - ".:/app_ghotos"
      - "./data_dev:/data/ghoto"
    depends_on:
      - db
    networks:
      - ghotos_dev
    stdin_open: true      
    tty: true         
  client:
    image: ghotos_client
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    volumes:
      - "./client/.:/app"
    ports:
      - "4080:8080"
    networks:
      - ghotos_dev
  db:
    container_name: ghotos_db
    image: mariadb:10.6
    volumes:
      - db_data_dev:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mgr
      MYSQL_DATABASE: ghotos
      MYSQL_USER: ghotos
      MYSQL_PASSWORD: ghotos_pass
    ports:
      - 3306:3306
    restart: always
    networks:
      - ghotos_dev
  adminer_dev:
    container_name: ghotos_adminer
    image: adminer:4.8.1
    restart: always
    ports:
      - 4091:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - ghotos_dev
