version: '3.8'
volumes:
  db_photos: {}

services:
  app:
    env_file: ".env"
    container_name: ghotos_app
    image: bluffy2006/ghotos    
    ports:
      - "4090:8080"        
    depends_on:
      - db
    environment: 
      - LOCAL_USER_ID=1000           
  db:
    container_name: ghotos_db
    image: yobasystems/alpine-mariadb:10.5
    volumes:
      - db_photos:/var/lib/mysql       
    environment:
      MYSQL_ROOT_PASSWORD: mgr
      MYSQL_DATABASE: $DB_USER
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS
    ports:
      - 4092:3306
    restart: always 
  adminer:
    container_name: ghotos_adminer
    image: adminer:4.8.1
    restart: always
    ports:
      - 4091:8080     
    environment:
      ADMINER_DEFAULT_SERVER: db  